<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Order extends Model
{
    use HasFactory;
    protected $keyType = 'string';
    public $incrementing = false;

    protected $casts = [
        'status' => 'boolean',
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function address()
    {
        return $this->belongsTo(Address::class);
    }

    public function products()
    {
        return $this->belongsToMany(Product::class)->withPivot(['quantity','price','variant'])->using(OrderProductPivot::class);
    }
  
    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function (Model $model) {
            $model->{$model->getKeyName()} = Str::uuid()->toString();
        });
    }
}
